### PR TITLE
Testing Push to ADARA-Neutrons Repo

### PR DESCRIPTION
**Pull request by jeeembo66**
I can't seem to git push the latest ADARA to this repo in GitHub... D-Oh. If you see this please help/advise. Thanks!

   Jeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeem :)

### CODE REVIEW

**Comment by gshipman** [comment]
Hey Jim! Should you be owner?


Galen



From: Dr. James A. Kohl ***@***.******@***.***>>
Date: Monday, Feb 27, 2023 at 3:38 PM
To: ADARA-Neutrons/adara ***@***.******@***.***>>
Cc: Subscribed ***@***.******@***.***>>
Subject: [EXTERNAL] [ADARA-Neutrons/adara] Testing Push to ADARA-Neutrons Repo (PR #1)


I can't seem to git push the latest ADARA to this repo in GitHub... D-Oh. If you see this please help/advise. Thanks!

Jeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeem :)

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/ADARA-Neutrons/adara/pull/1<https://urldefense.com/v3/__https://github.com/ADARA-Neutrons/adara/pull/1__;!!Bt8fGhp8LhKGRg!Ewh-1_yfWCie64tPHWT8uIc0anyDseH-DGMhStPzcneKAODh7skydPzCabXbnXCmFiaLkY761dT0WU2thuCZaaleCg$>

Commit Summary

  *   9d0fb91<https://urldefense.com/v3/__https://github.com/ADARA-Neutrons/adara/pull/1/commits/9d0fb9173e91de12ab197f7fff939d7da2de9ab7__;!!Bt8fGhp8LhKGRg!Ewh-1_yfWCie64tPHWT8uIc0anyDseH-DGMhStPzcneKAODh7skydPzCabXbnXCmFiaLkY761dT0WU2thuAVssaKvA$> Testing Push to ADARA-Neutrons Repo

File Changes

(1 file<https://urldefense.com/v3/__https://github.com/ADARA-Neutrons/adara/pull/1/files__;!!Bt8fGhp8LhKGRg!Ewh-1_yfWCie64tPHWT8uIc0anyDseH-DGMhStPzcneKAODh7skydPzCabXbnXCmFiaLkY761dT0WU2thuB43i7hCA$>)

  *   M README<https://urldefense.com/v3/__https://github.com/ADARA-Neutrons/adara/pull/1/files*diff-2b7814d3fca2e99e56c51b6ff2aa313ea6e9da6424804240aa8ad891fdfe0900__;Iw!!Bt8fGhp8LhKGRg!Ewh-1_yfWCie64tPHWT8uIc0anyDseH-DGMhStPzcneKAODh7skydPzCabXbnXCmFiaLkY761dT0WU2thuAm5prTgg$> (2)

Patch Links:

  *   https://github.com/ADARA-Neutrons/adara/pull/1.patch<https://urldefense.com/v3/__https://github.com/ADARA-Neutrons/adara/pull/1.patch__;!!Bt8fGhp8LhKGRg!Ewh-1_yfWCie64tPHWT8uIc0anyDseH-DGMhStPzcneKAODh7skydPzCabXbnXCmFiaLkY761dT0WU2thuBXl60xsA$>
  *   https://github.com/ADARA-Neutrons/adara/pull/1.diff<https://urldefense.com/v3/__https://github.com/ADARA-Neutrons/adara/pull/1.diff__;!!Bt8fGhp8LhKGRg!Ewh-1_yfWCie64tPHWT8uIc0anyDseH-DGMhStPzcneKAODh7skydPzCabXbnXCmFiaLkY761dT0WU2thuBoJm58gg$>

**Comment by jeeembo66** [comment]
Hey Galen! 😄

YES Please. 🙂  I'm the "last man standing" ha ha ha...!! ;-D

   Jeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeem :)

________________________________
From: Galen Shipman ***@***.***>
Sent: Monday, February 27, 2023 4:47 PM
To: ADARA-Neutrons/adara ***@***.***>
Cc: Kohl, James Arthur ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [ADARA-Neutrons/adara] Testing Push to ADARA-Neutrons Repo (PR #1)


Hey Jim! Should you be owner?


Galen



From: Dr. James A. Kohl ***@***.******@***.***>>
Date: Monday, Feb 27, 2023 at 3:38 PM
To: ADARA-Neutrons/adara ***@***.******@***.***>>
Cc: Subscribed ***@***.******@***.***>>
Subject: [EXTERNAL] [ADARA-Neutrons/adara] Testing Push to ADARA-Neutrons Repo (PR #1)


I can't seem to git push the latest ADARA to this repo in GitHub... D-Oh. If you see this please help/advise. Thanks!

Jeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeem :)

________________________________
You can view, comment on, or merge this pull request online at:

https://github.com/ADARA-Neutrons/adara/pull/1<https://urldefense.com/v3/__https://github.com/ADARA-Neutrons/adara/pull/1__;!!Bt8fGhp8LhKGRg!Ewh-1_yfWCie64tPHWT8uIc0anyDseH-DGMhStPzcneKAODh7skydPzCabXbnXCmFiaLkY761dT0WU2thuCZaaleCg$>

Commit Summary

* 9d0fb91<https://urldefense.com/v3/__https://github.com/ADARA-Neutrons/adara/pull/1/commits/9d0fb9173e91de12ab197f7fff939d7da2de9ab7__;!!Bt8fGhp8LhKGRg!Ewh-1_yfWCie64tPHWT8uIc0anyDseH-DGMhStPzcneKAODh7skydPzCabXbnXCmFiaLkY761dT0WU2thuAVssaKvA$> Testing Push to ADARA-Neutrons Repo

File Changes

(1 file<https://urldefense.com/v3/__https://github.com/ADARA-Neutrons/adara/pull/1/files__;!!Bt8fGhp8LhKGRg!Ewh-1_yfWCie64tPHWT8uIc0anyDseH-DGMhStPzcneKAODh7skydPzCabXbnXCmFiaLkY761dT0WU2thuB43i7hCA$>)

* M README<https://urldefense.com/v3/__https://github.com/ADARA-Neutrons/adara/pull/1/files*diff-2b7814d3fca2e99e56c51b6ff2aa313ea6e9da6424804240aa8ad891fdfe0900__;Iw!!Bt8fGhp8LhKGRg!Ewh-1_yfWCie64tPHWT8uIc0anyDseH-DGMhStPzcneKAODh7skydPzCabXbnXCmFiaLkY761dT0WU2thuAm5prTgg$> (2)

Patch Links:

* https://github.com/ADARA-Neutrons/adara/pull/1.patch<https://urldefense.com/v3/__https://github.com/ADARA-Neutrons/adara/pull/1.patch__;!!Bt8fGhp8LhKGRg!Ewh-1_yfWCie64tPHWT8uIc0anyDseH-DGMhStPzcneKAODh7skydPzCabXbnXCmFiaLkY761dT0WU2thuBXl60xsA$>
* https://github.com/ADARA-Neutrons/adara/pull/1.diff<https://urldefense.com/v3/__https://github.com/ADARA-Neutrons/adara/pull/1.diff__;!!Bt8fGhp8LhKGRg!Ewh-1_yfWCie64tPHWT8uIc0anyDseH-DGMhStPzcneKAODh7skydPzCabXbnXCmFiaLkY761dT0WU2thuBoJm58gg$>

**Comment by jeeembo66** [comment]
Any Luck, Galen...? ;-D

I don't see any change as yet from my side... 🤔

Are you the current owner...?

Please let me know if you're able to dust off this ancient GitHub repo - we're trying to update it to the latest internal ADARA Version 1.8.1 code base, for Open Source sharing, etc. 😃 👍

Thanks Much!
   Jeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeem :)

________________________________

**Comment by gshipman** [comment]
Just sent the invite!

Galen



From: Dr. James A. Kohl ***@***.******@***.***>>
Date: Monday, Feb 27, 2023 at 4:55 PM
To: ADARA-Neutrons/adara ***@***.******@***.***>>
Cc: Shipman, Galen M ***@***.******@***.***>>, Comment ***@***.******@***.***>>
Subject: [EXTERNAL] Re: [ADARA-Neutrons/adara] Testing Push to ADARA-Neutrons Repo (PR #1)


Any Luck, Galen...? ;-D

I don't see any change as yet from my side... 🤔

Are you the current owner...?

Please let me know if you're able to dust off this ancient GitHub repo - we're trying to update it to the latest internal ADARA Version 1.8.1 code base, for Open Source sharing, etc. 😃 👍

Thanks Much!
Jeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeem :)

________________________________

**Comment by jeeembo66** [comment]
Awesome! Got It! Thanks Galen! 😃

Do I need to be on any of the “teams” you have created, or are those just for managing the project and don’t carry any additional permissions, etc…?

Thanks Much!
   Jeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeem :)


From: Galen Shipman ***@***.***>
Date: Monday, February 27, 2023 at 7:40 PM
To: ADARA-Neutrons/adara ***@***.***>
Cc: Kohl, James Arthur ***@***.***>, Author ***@***.***>
Subject: [EXTERNAL] Re: [ADARA-Neutrons/adara] Testing Push to ADARA-Neutrons Repo (PR #1)
Just sent the invite!

Galen



From: Dr. James A. Kohl ***@***.******@***.***>>
Date: Monday, Feb 27, 2023 at 4:55 PM
To: ADARA-Neutrons/adara ***@***.******@***.***>>
Cc: Shipman, Galen M ***@***.******@***.***>>, Comment ***@***.******@***.***>>
Subject: [EXTERNAL] Re: [ADARA-Neutrons/adara] Testing Push to ADARA-Neutrons Repo (PR #1)


Any Luck, Galen...? ;-D

I don't see any change as yet from my side... 🤔

Are you the current owner...?

Please let me know if you're able to dust off this ancient GitHub repo - we're trying to update it to the latest internal ADARA Version 1.8.1 code base, for Open Source sharing, etc. 😃 👍

Thanks Much!
Jeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeem :)

________________________________

**Comment by jeeembo66** [comment]
I was able to add myself to the relevant teams, lol. 😃

Thanks Again Galen! ADARA is Alive and Well! 😃

   Jeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeem :)


From: Kohl, James Arthur ***@***.***>
Date: Tuesday, February 28, 2023 at 10:59 AM
To: ADARA-Neutrons/adara ***@***.***>, ADARA-Neutrons/adara ***@***.***>
Cc: Author ***@***.***>, Kohl, James Arthur ***@***.***>
Subject: Re: [EXTERNAL] Re: [ADARA-Neutrons/adara] Testing Push to ADARA-Neutrons Repo (PR #1)
Awesome! Got It! Thanks Galen! 😃

Do I need to be on any of the “teams” you have created, or are those just for managing the project and don’t carry any additional permissions, etc…?

Thanks Much!
   Jeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeem :)


From: Galen Shipman ***@***.***>
Date: Monday, February 27, 2023 at 7:40 PM
To: ADARA-Neutrons/adara ***@***.***>
Cc: Kohl, James Arthur ***@***.***>, Author ***@***.***>
Subject: [EXTERNAL] Re: [ADARA-Neutrons/adara] Testing Push to ADARA-Neutrons Repo (PR #1)
Just sent the invite!

Galen



From: Dr. James A. Kohl ***@***.******@***.***>>
Date: Monday, Feb 27, 2023 at 4:55 PM
To: ADARA-Neutrons/adara ***@***.******@***.***>>
Cc: Shipman, Galen M ***@***.******@***.***>>, Comment ***@***.******@***.***>>
Subject: [EXTERNAL] Re: [ADARA-Neutrons/adara] Testing Push to ADARA-Neutrons Repo (PR #1)


Any Luck, Galen...? ;-D

I don't see any change as yet from my side... 🤔

Are you the current owner...?

Please let me know if you're able to dust off this ancient GitHub repo - we're trying to update it to the latest internal ADARA Version 1.8.1 code base, for Open Source sharing, etc. 😃 👍

Thanks Much!
Jeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeem :)

________________________________

**Comment by gshipman** [comment]
Woot!


From: "Dr. James A. Kohl" ***@***.***>
Reply-To: ADARA-Neutrons/adara ***@***.***>
Date: Tuesday, February 28, 2023 at 8:53 AM
To: ADARA-Neutrons/adara ***@***.***>
Cc: "Shipman, Galen M" ***@***.***>, Comment ***@***.***>
Subject: [EXTERNAL] Re: [ADARA-Neutrons/adara] Testing Push to ADARA-Neutrons Repo (PR #1)

I was able to add myself to the relevant teams, lol. 😃

Thanks Again Galen! ADARA is Alive and Well! 😃

Jeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeem :)


From: Kohl, James Arthur ***@***.***>
Date: Tuesday, February 28, 2023 at 10:59 AM
To: ADARA-Neutrons/adara ***@***.***>, ADARA-Neutrons/adara ***@***.***>
Cc: Author ***@***.***>, Kohl, James Arthur ***@***.***>
Subject: Re: [EXTERNAL] Re: [ADARA-Neutrons/adara] Testing Push to ADARA-Neutrons Repo (PR #1)
Awesome! Got It! Thanks Galen! 😃

Do I need to be on any of the “teams” you have created, or are those just for managing the project and don’t carry any additional permissions, etc…?

Thanks Much!
Jeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeem :)


From: Galen Shipman ***@***.***>
Date: Monday, February 27, 2023 at 7:40 PM
To: ADARA-Neutrons/adara ***@***.***>
Cc: Kohl, James Arthur ***@***.***>, Author ***@***.***>
Subject: [EXTERNAL] Re: [ADARA-Neutrons/adara] Testing Push to ADARA-Neutrons Repo (PR #1)
Just sent the invite!

Galen



From: Dr. James A. Kohl ***@***.******@***.***>>
Date: Monday, Feb 27, 2023 at 4:55 PM
To: ADARA-Neutrons/adara ***@***.******@***.***>>
Cc: Shipman, Galen M ***@***.******@***.***>>, Comment ***@***.******@***.***>>
Subject: [EXTERNAL] Re: [ADARA-Neutrons/adara] Testing Push to ADARA-Neutrons Repo (PR #1)


Any Luck, Galen...? ;-D

I don't see any change as yet from my side... 🤔

Are you the current owner...?

Please let me know if you're able to dust off this ancient GitHub repo - we're trying to update it to the latest internal ADARA Version 1.8.1 code base, for Open Source sharing, etc. 😃 👍

Thanks Much!
Jeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeem :)

________________________________

**Pull request closed without merging**
